development:
  adapter: postgresql
  encoding: utf8
  database: login_development

test:
  adapter: postgresql
  encoding: utf8
  database: login_test

production:
  adapter: postgresql
  encoding: utf8
  database: login_production